version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-eks: circleci/aws-eks@2.2.0
  aws-ecr: circleci/aws-ecr@9.0.2
  kubernetes: circleci/kubernetes@1.3.0
jobs:

  deploy:
    circleci_ip_ranges: false # opts the job into the IP ranges feature
    docker:
      - image: 'cimg/python:3.10'
    resource_class: << parameters.resource_class >>
    parameters:
      resource_class: 
        description: |
          deploy to resource class
        type: string
      cluster-name:
        description: |
          Devnet cluster
        type: string
      docker-image-name:
        description: |
          api-gateway
        type: string
      version-info:
        description: |
          Latest
        type: string
      min-replicas:
        description: |
          number of min replicas to create
        type: string
      max-replicas:
        description: |
          number of max replicas to create
        type: string
      aws-region:
        description: |
          AWS region
        type: string
        default: 'eu-west-1'
      env-name:
        description: |
          env name for managing cluster host file
        type: string
      total_cpu:
        description: |
          total cpu alloction
        type: string
      request_cpu:
        description: |
          reqests cpu alloction
        type: string
      limit_memory:
        description: |
          limit memory allocation
        type: string
      request_memory:
        description: |
          reqests memory alloction
        type: string
      secret-name:
        description: |
          secret name for managing cluster host file
        type: string
      deployment-name:
        description: |
          deploy name for managing cluster host file
        type: string
      app-name:
        description: |
          app name for managing cluster host file
        type: string
    steps:
      - checkout
      - run:
          name: Create deployment manifest
          command: |
            BUILD_DATE=$(date '+%Y%m%d%H%M%S')
            cat kubernetes/deployment-template.yml |\
                sed "s|DOCKER_IMAGE_NAME|<< parameters.docker-image-name >>|g;\
                s|ENV_NAME|<< parameters.env-name >>|g;\
                s|BUILD_DATE_VALUE|$BUILD_DATE|g;\
                s|MIN_REPLICAS|<< parameters.min-replicas >>|g;\
                s|MAX_REPLICAS|<< parameters.max-replicas >>|g;\
                s|TOTAL_CPU|<< parameters.total_cpu >>|g;\
                s|REQUEST_CPU|<< parameters.request_cpu >>|g;\
                s|REQUEST_MEMORY|<< parameters.request_memory >>|g;\
                s|LIMIT_MEMORY|<< parameters.limit_memory >>|g;\
                s|SECRET_NAME|<< parameters.secret-name >>|g; \
                s|DEPLOYMENT_NAME|<< parameters.deployment-name >>|g;\
                s|APP_NAME|<< parameters.app-name >>|g;\
                s|VERSION_INFO_VALUE|<< parameters.version-info >>|g;" > kubernetes/deployment.yml
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          install-kubectl: true
          aws-region: << parameters.aws-region >>
      - kubernetes/create-or-update-resource:
          resource-file-path: 'kubernetes/deployment.yml'
          namespace: chatwoot
          get-rollout-status: true
          resource-name: deployment/<< parameters.deployment-name >>
  
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          name: staging-build
          auth:
            - aws-cli/setup:
                role_arn: "${AWS_ROLE_ARN}"
                profile_name: deltaexchange-oidc
          context: staging
          filters:
            branches:
              only:
                - devnet
          region: "${AWS_REGION}"
          account_id: ${AWS_ACCOUNT_ID}
          create_repo: true
          dockerfile: Dockerfile
          no_output_timeout: 30m
          profile_name: deltaexchange-oidc
          repo: chatwoot
          tag: ${CIRCLE_SHA1}
      # devnet ind deploy
      - deploy:
          name: devnet-india-sidekiq
          context: staging
          resource_class: delta-exchange/deploy-devnet
          filters:
            branches:
              only:
                - devnet
          cluster-name: devnet-delta-exchange
          min-replicas: '1'
          max-replicas: '1'
          env-name: devnet
          app-name: devnet-sidekiq
          secret-name: devnet-ind-sidekiq
          aws-region: $AWS_REGION
          docker-image-name: '${AWS_TOKYO_ECR_URL}/chatwoot:${CIRCLE_SHA1}'
          version-info: ${CIRCLE_SHA1}
          total_cpu: '2'
          request_cpu: '1'
          limit_memory: '500M'
          request_memory: '400M'
          deployment-name: 'staging-sidekiq'
          requires:
            - staging-build

      